/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TokensTokenIdRouteImport } from './routes/tokens/$tokenId'
import { Route as ApiV1TokensRouteImport } from './routes/api.v1.tokens'
import { Route as ApiV1FrameworkRouteImport } from './routes/api.v1.framework'
import { Route as ApiV1FaqRouteImport } from './routes/api.v1.faq'
import { Route as ApiV1TokensTokenIdRouteImport } from './routes/api.v1.tokens.$tokenId'

const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TokensTokenIdRoute = TokensTokenIdRouteImport.update({
  id: '/tokens/$tokenId',
  path: '/tokens/$tokenId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1TokensRoute = ApiV1TokensRouteImport.update({
  id: '/api/v1/tokens',
  path: '/api/v1/tokens',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1FrameworkRoute = ApiV1FrameworkRouteImport.update({
  id: '/api/v1/framework',
  path: '/api/v1/framework',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1FaqRoute = ApiV1FaqRouteImport.update({
  id: '/api/v1/faq',
  path: '/api/v1/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1TokensTokenIdRoute = ApiV1TokensTokenIdRouteImport.update({
  id: '/$tokenId',
  path: '/$tokenId',
  getParentRoute: () => ApiV1TokensRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/faq': typeof FaqRoute
  '/tokens/$tokenId': typeof TokensTokenIdRoute
  '/api/v1/faq': typeof ApiV1FaqRoute
  '/api/v1/framework': typeof ApiV1FrameworkRoute
  '/api/v1/tokens': typeof ApiV1TokensRouteWithChildren
  '/api/v1/tokens/$tokenId': typeof ApiV1TokensTokenIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/faq': typeof FaqRoute
  '/tokens/$tokenId': typeof TokensTokenIdRoute
  '/api/v1/faq': typeof ApiV1FaqRoute
  '/api/v1/framework': typeof ApiV1FrameworkRoute
  '/api/v1/tokens': typeof ApiV1TokensRouteWithChildren
  '/api/v1/tokens/$tokenId': typeof ApiV1TokensTokenIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/faq': typeof FaqRoute
  '/tokens/$tokenId': typeof TokensTokenIdRoute
  '/api/v1/faq': typeof ApiV1FaqRoute
  '/api/v1/framework': typeof ApiV1FrameworkRoute
  '/api/v1/tokens': typeof ApiV1TokensRouteWithChildren
  '/api/v1/tokens/$tokenId': typeof ApiV1TokensTokenIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/faq'
    | '/tokens/$tokenId'
    | '/api/v1/faq'
    | '/api/v1/framework'
    | '/api/v1/tokens'
    | '/api/v1/tokens/$tokenId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/faq'
    | '/tokens/$tokenId'
    | '/api/v1/faq'
    | '/api/v1/framework'
    | '/api/v1/tokens'
    | '/api/v1/tokens/$tokenId'
  id:
    | '__root__'
    | '/'
    | '/faq'
    | '/tokens/$tokenId'
    | '/api/v1/faq'
    | '/api/v1/framework'
    | '/api/v1/tokens'
    | '/api/v1/tokens/$tokenId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FaqRoute: typeof FaqRoute
  TokensTokenIdRoute: typeof TokensTokenIdRoute
  ApiV1FaqRoute: typeof ApiV1FaqRoute
  ApiV1FrameworkRoute: typeof ApiV1FrameworkRoute
  ApiV1TokensRoute: typeof ApiV1TokensRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tokens/$tokenId': {
      id: '/tokens/$tokenId'
      path: '/tokens/$tokenId'
      fullPath: '/tokens/$tokenId'
      preLoaderRoute: typeof TokensTokenIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/tokens': {
      id: '/api/v1/tokens'
      path: '/api/v1/tokens'
      fullPath: '/api/v1/tokens'
      preLoaderRoute: typeof ApiV1TokensRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/framework': {
      id: '/api/v1/framework'
      path: '/api/v1/framework'
      fullPath: '/api/v1/framework'
      preLoaderRoute: typeof ApiV1FrameworkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/faq': {
      id: '/api/v1/faq'
      path: '/api/v1/faq'
      fullPath: '/api/v1/faq'
      preLoaderRoute: typeof ApiV1FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/tokens/$tokenId': {
      id: '/api/v1/tokens/$tokenId'
      path: '/$tokenId'
      fullPath: '/api/v1/tokens/$tokenId'
      preLoaderRoute: typeof ApiV1TokensTokenIdRouteImport
      parentRoute: typeof ApiV1TokensRoute
    }
  }
}

interface ApiV1TokensRouteChildren {
  ApiV1TokensTokenIdRoute: typeof ApiV1TokensTokenIdRoute
}

const ApiV1TokensRouteChildren: ApiV1TokensRouteChildren = {
  ApiV1TokensTokenIdRoute: ApiV1TokensTokenIdRoute,
}

const ApiV1TokensRouteWithChildren = ApiV1TokensRoute._addFileChildren(
  ApiV1TokensRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FaqRoute: FaqRoute,
  TokensTokenIdRoute: TokensTokenIdRoute,
  ApiV1FaqRoute: ApiV1FaqRoute,
  ApiV1FrameworkRoute: ApiV1FrameworkRoute,
  ApiV1TokensRoute: ApiV1TokensRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
